# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pr1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 418)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("\n"
"    background-color: #121212;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 0, 401, 361))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #1E1E1E;\n"
"    border-radius: 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.titleLabel = QtWidgets.QLabel(self.frame)
        self.titleLabel.setGeometry(QtCore.QRect(60, 30, 291, 41))
        self.titleLabel.setStyleSheet("QLabel {\n"
"    color: #FF6B00;\n"
"    font-size: 42px;\n"
"    font-weight: bold;\n"
"}")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.subtitleLabel = QtWidgets.QLabel(self.frame)
        self.subtitleLabel.setGeometry(QtCore.QRect(70, 80, 161, 31))
        self.subtitleLabel.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 18px;\n"
"    letter-spacing: 3px;\n"
"}")
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.loginButton = QtWidgets.QPushButton(self.frame)
        self.loginButton.setGeometry(QtCore.QRect(100, 140, 201, 51))
        self.loginButton.setStyleSheet("QPushButton {\n"
"    background-color: #FF6B00;\n"
"    color: white;\n"
"    border: 2px solid #FF6B00;\n"
"    border-radius: 12px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF8C42;\n"
"    border: 2px solid #FFFFFF;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #D95700;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.registerButton = QtWidgets.QPushButton(self.frame)
        self.registerButton.setGeometry(QtCore.QRect(90, 210, 221, 51))
        self.registerButton.setStyleSheet("QPushButton {\n"
"    background-color: #FF6B00;\n"
"    color: white;\n"
"    border: 2px solid #FF6B00;\n"
"    border-radius: 12px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF8C42;\n"
"    border: 2px solid #FFFFFF;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #D95700;\n"
"}")
        self.registerButton.setObjectName("registerButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(80, 280, 241, 20))
        self.label.setStyleSheet("QLabel {\n"
"    color: #888888;\n"
"    font-size: 14px;\n"
"}")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MOTO DRIVE - Мотосалон"))
        self.titleLabel.setText(_translate("MainWindow", "MOTO DRIVE"))
        self.subtitleLabel.setText(_translate("MainWindow", "МОТОСАЛОН"))
        self.loginButton.setText(_translate("MainWindow", "УВІЙТИ"))
        self.registerButton.setText(_translate("MainWindow", "РЕЄСТРАЦІЯ"))
        self.label.setText(_translate("MainWindow", "Ваш шлях починається тут ..."))
